# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-02 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodspark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Sent'), (1, 'Cancelled')], default=0),
        ),
    ]
